
export const GET_DATA_PRODUCTS_ONE_BEGIN = "GET_DATA_PRODUCTS_ONE_BEGIN";
export const GET_DATA_PRODUCTS_ONE_SUCCESS = "GET_DATA_PRODUCTS_ONE_SUCCESS";
export const GET_DATA_PRODUCTS_ONE_FAIL = "GET_DATA_PRODUCTS_ONE_FAIL";